package me.kqlqk.behealthy.workout_service.model.enums;

public enum MuscleGroup {
    SHOULDERS,
    CHEST,
    TRICEPS,
    BACK,
    BICEPS,
    FOREARMS,
    LOWER_BACK,
    ABS,
    BUTTOKS,
    QUADRICEPS,
    LEGS_BICEPS,
    CALVES,

    SHOULDERS_CHEST,
    SHOULDERS_BACK,
    CHEST_TRICEPS,
    BACK_BICEPS,
    BICEPS_FOREARMS,
    LEGS_BICEPS_LOWER_BACK_,
    LEGS_BICEPS_BUTTOKS,
    LOWER_BACK_BUTTOKS,
    QUADRICEPS_BUTTOKS,
    QUADRICEPS_LEGS_BICEPS
}
